name: CodeQL Analysis

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  CodeQL-Analysis:
    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          fetch-depth: 0
          submodules: true

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2

      - name: Build
        run: make build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
