name: Docker Deploy

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  resolve-registry:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.registry.outputs.matrix }}
      tag: ${{ steps.git_info.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: registry
        run: |
          JSON=$(cat .github/workflows/registry.json | tr '\n' ' ' | sed 's/ //g')
          echo "::set-output name=matrix::$JSON"

      - id: git_info
        run: |
          tag=$(echo ${{ github.ref }} | rev | cut -d/ -f1 | rev)
          echo "::set-output name=tag::$tag"

  build:
    runs-on: ubuntu-latest
    needs: [ resolve-registry ]
    strategy:
      matrix: ${{fromJSON(needs.resolve-registry.outputs.matrix)}}
      alpine: [ 3.16, 3.17 ]

    env:
      id: ${{ secrets[matrix.id] }}
      token: ${{ secrets[matrix.token] }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          fetch-depth: 0
          submodules: true

      - name: Log into registry ${{ matrix.name }}
        uses: docker/login-action@v1
        with:
          registry: ${{ matrix.register }}
          username: ${{ env.id }}
          password: ${{ env.token }}

      - name: Set Up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Build and Push ${{ matrix.name }}
        run: |
          REPO=${{ matrix.push_link }} ALPINE_VERSION=${{ alpine }} VERSION=${{ needs.resolve-registry.outputs.tag }} docker buildx bake --file docker/docker-bake.hcl --push --set "*.platform=linux/arm64,linux/amd64,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6"

  release:
    runs-on: ubuntu-latest
    needs: [ build ]

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true